- name: "HTH | Firefox | Run assertions"
  ansible.utils.validate:
    data: "{{ firefox }}"
    criteria: "{{ lookup('file', 'assertions/criteria/firefox-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
    - firefox is defined

- name: "HTH | Firefox | Gather package facts"
  ansible.builtin.package_facts:
    manager: "auto"
  when:
    - firefox.gather_facts is not defined or firefox.gather_facts

- ansible.builtin.import_tasks: snap.yml
  when:
    - firefox.snap is defined
    - ansible_distribution in ['Debian', 'Ubuntu']

- ansible.builtin.import_tasks: esr.yml
  when:
    - firefox.esr is defined
    - ansible_distribution in ['Debian', 'Ubuntu']

- ansible.builtin.import_tasks: mozilla.yml
  when:
    - firefox.mozilla is defined
    - ansible_distribution in ['Debian', 'Ubuntu']
