- name: Firefox | Assert required inputs
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost

- name: Firefox | Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"
  when: firefox.gather_facts is not defined or firefox.gather_facts

- ansible.builtin.import_tasks: mozilla.yml
  when:
    - firefox.mozilla is defined
    - ansible_distribution in ['Debian', 'Ubuntu']
