# This file contains configuration tasks related to installation of Firefox
# via Canonical's Snap packages.

- name: "HTH | Firefox | Install snap package"
  community.general.snap:
    name: firefox
    state: latest
  when:
    - firefox.snap is defined
    - firefox.snap

- name: "HTH | Firefox | Remove snap package"
  community.general.snap:
    name: firefox
    state: absent
  when:
    - firefox.snap is defined
    - not firefox.snap
