# This files contains assertions for required input variables used to
# perform the tasks in this role.

- name: Firefox | Assert 'firefox' input
  ansible.builtin.assert:
    that:
      - firefox is defined
      - firefox is mapping

- name: Firefox | Validate input schema
  ansible.utils.validate:
    data: "{{ firefox }}"
    criteria:
      - "{{ lookup('file',  './criteria/firefox-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  when:
  - firefox is defined
